# Generated by Django 5.2.4 on 2025-08-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500)),
                ('cart_title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
