# Generated by Django 5.2.4 on 2025-08-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='pricess',
        ),
    ]
