# Generated by Django 5.2.4 on 2025-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardss', '0002_rename_price_product_pricess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pricess',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
