# Generated by Django 5.2.4 on 2025-08-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardss', '0004_alter_product_pricess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pricess',
            field=models.IntegerField(),
        ),
    ]
